### ISSUE TITLE
Info about 3.2w driver modification 

### ISSUE THREAD

**Issue by satfan52** [jmharvey1/SdrCwXcvr#1]
Hello,
Thanks for the great video, it is very impressive and very well made. 

I am also using the same ebay driver 3.2 w module that I bought for 7 euros on AliExpress. 

1),I noticed that the Gain in the 160m band drops by about 3 dB compared to the one on higher bands. Did you experience the sane issue? Is this why you replaced the 2 native chokes by some 220uh ones?? If you could post a picture of the modified board so I see better how you have done it, it would be greatly appreciated.

2) could you also describe a little bit more the added value of the RC  feedback mechanism you added  to the module (with the value of the components). I noticed that the Gain of this little Power module is quite high, around 45dB and quite flat over all HF bands (apart from the 160m band where it is about 3dB lesser), so I wonder what is the purpose of adding this feedback network. Again a picture would be much appreciated 

Best Regards 
Peter

**Comment by jmharvey1** [comment]
Peter,
Thanks for your interest in the project.
Yes. That's exactly what the 220 uh chokes are for. But to be clear, In my case the low end of this amp is 75 Mtrs (3.5Mhz). So can't say for sure what these mods will do at 160m.
Also I don't know what the output stage active device is, but given how its biased, I treated it like it was an N channel enhancement mode Mosfet. So the feedback network is nothing more than an 680 ohm resistor in series with a 0.1mfd capacitor connected to the drain (the junction of the second 220uh choke and Amp's output coupling capacitor)  and gate (the junction of the 3.3k bias resistor and the output coupling capacitor  of the first stage). The value of 680 is not magical for the resistor, and you could use something smaller or larger, depending on where you want to go with the overall gain of the unit.. In my case I was looking more for the flattest square wave possible ( at the low end) than a specific gain.
Hopefully, this view will give the detail you're looking for. 
![3wattDriverAmp](https://user-images.githubusercontent.com/7501981/54431973-37019980-46fe-11e9-9757-4f5ea995ec54.JPG)
       
Tnx,
Jim (KW4KD)

**Comment by satfan52** [comment]
Thanks for all the info and the picture !!

I am wondering if you  could you quantify what was the effect of replacing
the chokes  on the Gain of the device in the 75 and 80m band? One dB?,
three dB additional gain? Only the choke please, not the effect of the
feedback resistor. This will give me some benchmark indication for
comparison purpose.

Regarding the feedback resistor, it is probably not needed in my case as I
want the amp to climb up to 145 Mhz. I would however be curious if you
could quantify what is the effect of adding this feedback resistor either
in terms of gain flatness, gain reduction, bandwidth reduction etc.. It
maybe useful for me at a later stage and this type of benchmark info is
useful

This amp uses two  mmic which are  marched on the input and output not unmatched Mos type of transistors, though negative feedback works with this too I guess, according to my seller the devices are SBA5089 and RD01MU

Thanks

**Comment by jmharvey1** [comment]
Sorry for the slow response. I probably need to change the E-Mail account I have github linked to.
Your questions are good ones. But unfortunately today I have little quantitative data on the effect of these mods.
As sort of an explanation why, please read on:
I’m using this amp as a driver for a set of cheap “finals” (IRF-530’s) in a CW transmitter. To keep the final’s efficiency high (power dissipation low), my driving signal is a square wave, not a sine wave. 
The idea being that the finals should be either “Full Off”, or “Full On”, not somewhere in between. With the stock amp, at 80 meters, what I was seeing, on the scope, was not a square wave, but a trapezoidal wave. And the finals reflected this by overheating on 80 meters, but not on 40, even though they were switching faster on 40 Mtrs.  Changing the stock inductors to 220uh, and adding the feedback network, got me the square wave I was looking for (and significantly reduced “heating” on 80). 
Since I was only interested in a specific set of frequencies, I didn’t try to “generalize” the results, and do a plot of gain versus all frequencies.
Your point about about the output device used in the module (FET vs MMIC) is valid.  
I’ve been using LT spice to better understand what’s going on in the PA. To do that, I needed to model the output of the driver (the 3.2W amp).
I have yet to find a Mosfet to do it. But have made a fair model (at least for my purposes) using a pair of bipolar transistors.  So if you do have a part number for this device, I’d appreciate your passing it along, so I can compare it to my “by guess by golly” model.
Again, thanks for the interest in this project, and hope you have some luck with what you’re working on there.

Jim (KW4KD)

**Comment by satfan52** [comment]
OK Clear. The two mmic used (according to my seller) are : SBA5089 and RD01MU Thanks

**Comment by satfan52** [comment]
I realize the that model I bought is not the exactly same than yours. However it is very similar.

 I replaced the two chokes by two 22uh ones and it indeed dramatically improved the gain in the 160m and 80m, I gained 6 or 7 dB and the gain is really much flatter in the 1mhz-5mhz range. Thanks for the tip 

I was less lucky with the feedback resistors. I first tried with a 470 ohm resistor on the final, I was very happy at first because I managed to reduce the gain from 47dB to 40dB with an ultra flat frequency response up to 150 Mhz (less than 0.5dB variation, between 1 and 150 Mhz beautiful result).  However my happiness was quite short, for some reasons I still don't understand I killed the first stage during one of my measurements. The nanovna I use has an output level in the order of -17 to -12 dBm and I used a 10dB atenuator in front of it so I suspect what killed the first stage is the feedback resistor, maybe I should increase from 470 ohm to 650 ohm or so. What is your experience playing with this feedback resistor ?  Have you also lost some devices during your tests ?

**Comment by jmharvey1** [comment]
Interesting, I ran into the same issue. In fact, I’m waiting right now for a replacement IC (for the first stage). 
FWIW, this https://www.ebay.com/itm/1MHZ-1000MHZ-3W-35DB-HF-VHF-UHF-FM-transmitter-RF-Power-Amplifier-F-Ham-Radio/192764700606?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649 is the unit I was working with, when I “smoked” it.  In my case, I don’t think it was because it was being overdriven at the input. As that signal was < +3dbm.
Also, at the time of it’s demise, there was no feed back network on the first stage. But I was playing with 2nd stage feed back network. Caught me completely by surprise. My interest in this board is only for HF work (i.e. feq < 28 Mhz). And my scope is a 100 Mhz unit. So I’m guessing that the 2nd stage may have broke into oscillation (at some UHF freq). And through the feed back network, that oscillation overloaded the 1st stage. But again it’s just a guess.
Am curious, was the unit you were using the same as that of the hyperlink?

Tnx,
Jim(KW4KD)
.

**Comment by satfan52** [comment]
Hi Jim,

Interesting indeed. 

1) Yes I use the very same unit than the one you have just ordered.  I have already smoked two of them, always the first stage, never the second one. The first one because I simply over-drove it and the second one because of my experiments with that feedback resistor. 

2) Please find attached my measurements of the GAIN (S21) and Input SWR of the unmodified device without the choke modifications and without any feedback resistor. My measurement and the VNA calibration were made with a 20 dB attenuator at the input of the amp and 30dB attenuator at the Output of the amp.  To get the Gain, you therefore need to add 50 dB (yes 50!!!) to the S21 figures indicated by the different markers  !!!! In HF, the gain of this device is HUGE Jim, in the order of 45-50dB !!!! This is MUCH MUCH more than the 35dB claimed by the vendor...

![predriver-naked-20IN-30OUT](https://user-images.githubusercontent.com/14941529/71935439-0f0c8680-31a7-11ea-96cb-c43554ddadc8.png)

3) I killed my first device with an input signal in the order of -2dBm !!!! My redpitaya SDR transceiver outputs about 8dBm, and with a 10dB attenuator in front of it I killed the first stage !!  I learned the hard way that in my use-case to be able to output about 2W the optimal input level is no more than -10 to -15 dBm !!! So I am afraid that with +3dBm you largely smoked the input stage as well ...

4) Since the first stage of my amp is dead, I have disabled it and I now attack directly the second stage, I still get about 27dB gain in HF !! and this is more than enough for my specific use-case to drive my pushpull MRF436 driver followed by my SD2931-10 pushpull PA

5) Regarding my test with the feedback resistor, I indeed noticed some sudden instabilities during some of the gain measurements sweeps. One of those instabilities just killed the first stage as a matter of fact.... My NANO VNA delivers about -13 dBm, I think that when the first stage blew up I was only using a -10dB attenuator at the input, so -23 dBm input power  with the attenuator; it is clearly the effect of the feedback resistor that killed the first stage and not the input level .

6)  The feedback resistors changes the output impedance of the first stage and this may indeed result in some instabilities, that is my best educated guess, or wet finger in the wind. Why those instabilities seems to affect the first stage only and not the second one seems to me logical as the effect of the feedback resistor is precisely to reduce the gain at lower frequencies of the second stage and to stabilize it (assuming the second stage behaves like a classical single LDMOS or VDMOS transistor). 

6) I used a value of 450 ohm for the feedback resistor. As the  shunt resistor at the output of the first stage / input of the second stage is 220 ohm, this makes potentially in the worst case, a feedback ratio of 220/(220+450) or roughly 1/3 (so about 10 dB in terms of power ratio). This maybe a bit too much for that poor first stage....I think I will make my next series of tests with a much higher value feedback resistor (1K) and/or  I will reduce that shunt 220 ohm resistor in the range of 25 - 100 ohms (but then the gain reduction may just be way too high for my use-case, so to be tried).

**Comment by jmharvey1** [comment]
Thanks for the quick response. And I appreciate you including the VNA response curves. I don’t have a piece of test gear like that. So it represents new info that I hadn’t seen before.
Just checked the package tracking site. It looks like the 1st stage IC should arrive tomorrow. The bad news is I’m going to be gone most of the day, and will not be able to do anything further until Thursday. 

It might not be clear about what I’ve done here. So let me provide some background:
1. The original Amp ( https://www.ebay.com/itm/15V-35dB-1MHz-700Mhz-433Mhz-3-2W-HF-VHF-UHF-FM-RF-Power-Amplifier-Amp-Radio-Ham/322469066428?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649  ) has never failed.

2. I bought Amp #2 (The one you and I are having trouble with) looking for a cheaper alternative.

3. With Amp #2 I replaced the inductors (on both stages) with 220 uh ( Just like I did with original amp)

4. Initially this amp worked fine into a 50 dummy load, but the 2nd stage failed immediately when I tried to use it as the driver to a 70W PA. (the same PA that the original Amp drives without issue)

5. So I replaced the 2nd stage (a FET) and added a feedback network (stage 2 only). 

6. At this point amp #2, had  about a 3db advantage over the original amp, and was stable into a resistive load, a low pass filter network, and into the 70W PA working into a dummy load thru the appropriate low pass filter on all bands (20 thru 80 mtrs) . On 80 & 40 meters this configuration worked well into an antenna. But on 30 & 20 meters the PA’s output was dramatically reduced (i.e. ~70W out on 80 & 40 vs <10 watts on 20 & 30 mtrs)

7. At this point, I started trying different configurations of the 2nd stage feed back network. That’s when the 1st stage died, and testing stopped due to lack of replacement parts.

I’ll report further when the part arrives and I can get back to testing.

Longer term, I’m looking at taking what I learn here, and scratch build a push-pull amp that can output 3 – 5 Watts. The reason being I think the 70W PA will perform better when driven by an “untuned” balanced source rather than the single ended output found in the units we’re working with now.

Tnx & GL with you efforts there,

Jim (KW4KD)

**Comment by satfan52** [comment]
Hey Jim,

Thanks for the background, yes quite interesting. It is really funny
because a similar story  happened to me. I also first bought amp1 like you,
then blew it up like you and found amp2 as a cheaper alternative. In my
view amp2 is less powerful than amp1, I didn't had the time to make
accurate measurements (I own an accurate power meter, so that is next when
I receive my new boards just oredered) but from what I recall amp2 delivers
about 2W whereas amp1 goes up to 3. If you caWhen I receive the new amp2
boards that I just ordered, I will tell you exactly but I am afraid you
will have to wait a few weeks.

I got most of the story right except the part where you replaced the second
stage of amp2. Please share with me what is the replacement part you are
using.

My amp2 with its own heatsink is rock fixed to the larger heatsink of my
PA, so it is quite well cooled, at least better than if it was not attached
to it

I would really strongly encourage you to invest in a nanovna V1, I paid
mine 35 euros (40 USD), it is available on e-bay, aliexpress, etc... This
little device is a paradigm change on its own for us (hams ). Before the
area Nanovna, the least expensive similar device you could buy was costing
in the order of 250 - 300 USD, so what the developers of the nanovna have
done is really outstanding. I use the nanovna-saver software and as you
see  it is quite profesional. For HF and would even say up to 500 Mhz, the
nanovna is accurate enough. I own 3 other vna, the most expensive costing
500 USD (GC7105A) and quite frankly I do most of my HF amplifuer
measurement work with the nanovna because the dynamic range is sufficient
and because I know that if I blew it, it will be cheap to buy another.

Keep me informed of your progress
Peter

**Comment by jmharvey1** [comment]
Peter,
I’ll write more when I have more to report. But for a immediate response:
You asked, “What did I replace the 2nd stage with?”. I replaced it with a PD85004. 
Attached is the data sheet for this device.
Based on the package markings found on the original part, I believe the PD85004 is an appropriate replacement. Spec wise, it’s a good fit for this circuit/application.
My unit, with a ~12V supply generates ~ 2watts (sine wave). Because both amps share same final stage circuit configuration, I think this amp could also develop ~3.2 watts with a 15volt supply. But to be clear, I have yet to test it with a 15V supply, so its just a guess.  But given Amp #2 was fabricated using genuine parts, the PD85004 spec sheet suggests its can. 
That brings me to another thought. I suspect the out of the box version of this amp may not be built from quality parts. That could explain why we experienced some of the failures we have.

As for your VNA, thanks for the additional info. From your attachment, I noticed it was using a python program (GUI) to process the signals. Where did that come from?
BTW: Just got back from a weekly breakfast with our local group. One of the guys brought in a nanoVNA. He says that there are variants on the market, (i.e., some with internal battery, and some not)Regardless, between what you’ve shown me, what he had to say about it, and seeing it first person, I’m putting it on the “next thing to get” list. So again, thanks for sharing what you’re dong there.

73,
Jim (KW4KD)

PS: The 1st stage replacement IC (SBF5089Z) arrived yesterday, and my amp #2 is back running to the same performance numbers before I destroyed the 1st stage. As reported earlier while it works well as a stand alone Amp. It still does not play nicely with the 70W PA on 20 & 30 meters (40 & 80 mtrs, its just fine)

**Comment by satfan52** [comment]
Thanks Jim,

Thanks for all the info. I would start to check what is the gain of your PA over the frequency range 1-60 Mhz, maybe it has less gain on upper HF bands and the amp2 driver has nothing to do with that problem. A Nanovna sweep will do that for you. 

more technical info on the nanovna
https://github.com/ylabrj/NanoVNA_Load_Windows10

the whole story (several articles)
https://www.rtl-sdr.com/tag/nanovna/

the software that makes it look so good and so proffesional 
https://github.com/mihtjel/nanovna-saver
A bit of safety warning regarding the use of the Nanovna hardware with the nanovna-saver software; the nanovna sweeps continuously once it is turned on, so even if you didn't request nanovna to sweep via  the UI of nanovna-saver, the actual nanovna  hardware will still be sweeping based on the last parameter entered; rf will be exiting port0 and if  an amplifier is connected to port0 it will amplify whatever rf exits ports 0, this can be dangerous, the amplifier should be disabled or disconnected when no measurements are done, 

Advise, buy the cheapest version with a battery and use the software above
I bought the model with the standard screen, battery, the calib kit for 35 EUR about 40-41 USD I think

two different versions of nanovna 2 are in the pipeline,  one of them will cover up to 3 Ghz  and will be including HF bands.

 this software. This de
